export const achievementsSeed = [
  {
    key: 'first_habit',
    name: 'First Step',
    description: 'Complete your first habit.',
    category: 'habits',
    icon: 'CheckCircle2',
    xpReward: 50,
    condition: {
      type: 'habits_completed',
      threshold: 1,
    },
  },
  {
    key: 'habit_apprentice',
    name: 'Habit Apprentice',
    description: 'Complete 10 habits total.',
    category: 'habits',
    icon: 'Award',
    xpReward: 150,
    condition: {
      type: 'habits_completed',
      threshold: 10,
    },
  },
  {
    key: 'habit_master',
    name: 'Habit Master',
    description: 'Complete 100 habits total.',
    category: 'habits',
    icon: 'ShieldAlert',
    xpReward: 500,
    condition: {
      type: 'habits_completed',
      threshold: 100,
    },
  },
  {
    key: 'focus_starter',
    name: 'Timer Started',
    description: 'Complete your first focus session.',
    category: 'focus',
    icon: 'Play',
    xpReward: 50,
    condition: {
      type: 'focus_sessions',
      threshold: 1,
    },
  },
  {
    key: 'focus_depth',
    name: 'Deep Worker',
    description: 'Focus for a total of 120 minutes (2 hours).',
    category: 'focus',
    icon: 'Brain',
    xpReward: 200,
    condition: {
      type: 'focus_minutes',
      threshold: 120,
    },
  },
  {
    key: 'focus_master',
    name: 'Focus Titan',
    description: 'Focus for a total of 600 minutes (10 hours).',
    category: 'focus',
    icon: 'Zap',
    xpReward: 600,
    condition: {
      type: 'focus_minutes',
      threshold: 600,
    },
  },
  {
    key: 'streak_3',
    name: 'Consistency Kickoff',
    description: 'Reach a streak of 3 days.',
    category: 'streaks',
    icon: 'Flame',
    xpReward: 100,
    condition: {
      type: 'current_streak',
      threshold: 3,
    },
  },
  {
    key: 'streak_7',
    name: 'Unstoppable Week',
    description: 'Reach a streak of 7 days.',
    category: 'streaks',
    icon: 'CalendarDays',
    xpReward: 250,
    condition: {
      type: 'current_streak',
      threshold: 7,
    },
  },
  {
    key: 'streak_30',
    name: 'Month of Mastery',
    description: 'Reach a streak of 30 days.',
    category: 'streaks',
    icon: 'Crown',
    xpReward: 1000,
    condition: {
      type: 'current_streak',
      threshold: 30,
    },
  },
  {
    key: 'level_5',
    name: 'Leveling Up',
    description: 'Reach Level 5.',
    category: 'general',
    icon: 'Sparkles',
    xpReward: 200,
    condition: {
      type: 'level_reached',
      threshold: 5,
    },
  },
  {
    key: 'level_10',
    name: 'Ascended Practitioner',
    description: 'Reach Level 10.',
    category: 'general',
    icon: 'Trophy',
    xpReward: 500,
    condition: {
      type: 'level_reached',
      threshold: 10,
    },
  },
];
