export const habitTemplatesSeed = [
  {
    name: 'Morning Reflection',
    description: 'Spend 5 minutes reflecting on your goals for the day.',
    category: 'mindfulness',
    frequency: 'daily',
    difficulty: 'easy',
    icon: 'Sun',
    isSystem: true,
  },
  {
    name: 'Stay Hydrated',
    description: 'Drink at least 8 glasses of water today.',
    category: 'health',
    frequency: 'daily',
    difficulty: 'easy',
    icon: 'Droplet',
    isSystem: true,
  },
  {
    name: 'Read 10 Pages',
    description: 'Read 10 pages of a non-fiction or educational book.',
    category: 'learning',
    frequency: 'daily',
    difficulty: 'medium',
    icon: 'BookOpen',
    isSystem: true,
  },
  {
    name: 'Cardio Exercise',
    description: 'Perform 30 minutes of running, cycling, or active cardio.',
    category: 'fitness',
    frequency: 'daily',
    difficulty: 'medium',
    icon: 'Activity',
    isSystem: true,
  },
  {
    name: 'Daily Planning',
    description: 'Plan your schedule, tasks, and priorities for the next day.',
    category: 'productivity',
    frequency: 'daily',
    difficulty: 'easy',
    icon: 'Calendar',
    isSystem: true,
  },
  {
    name: 'Deep Coding Session',
    description: 'Focus on core programming or feature building without distractions.',
    category: 'productivity',
    frequency: 'daily',
    difficulty: 'hard',
    icon: 'Code2',
    isSystem: true,
  },
  {
    name: 'Gratitude Journaling',
    description: 'Write down three things you are grateful for today.',
    category: 'mindfulness',
    frequency: 'daily',
    difficulty: 'easy',
    icon: 'Heart',
    isSystem: true,
  },
  {
    name: 'Creative Writing',
    description: 'Spend 15-30 minutes writing or brainstorming creative projects.',
    category: 'creativity',
    frequency: 'daily',
    difficulty: 'medium',
    icon: 'PenTool',
    isSystem: true,
  },
  {
    name: 'Connect with a Friend',
    description: 'Reach out to a friend or family member for a meaningful conversation.',
    category: 'social',
    frequency: 'weekly',
    difficulty: 'easy',
    icon: 'MessageSquare',
    isSystem: true,
  },
  {
    name: 'Weekly Review',
    description: 'Review your achievements, habits, and learnings from the past week.',
    category: 'productivity',
    frequency: 'weekly',
    difficulty: 'medium',
    icon: 'BarChart2',
    isSystem: true,
  },
];
